language: go

dist: trusty
sudo: required

go: 1.7.x

env: DESKTOP=true ANDROID=false QT_QMAKE_CGO=true

matrix:
  include:
    - os: linux
      env: DESKTOP=true ANDROID=false QT_PKG_CONFIG=true PKG_CONFIG_PATH=/opt/qt58/lib/pkgconfig QT_DOC_DIR=/opt/qt58/doc QT_MISC_DIR=/opt/qt58

    - os: linux
      env: DESKTOP=false ANDROID=true

    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=true ANDROID=false

    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=true ANDROID=false QT_HOMEBREW=true

    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=false ANDROID=true

    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=false ANDROID=false IOS=true

    - os: osx
      osx_image: xcode8.2
      env: DESKTOP=false ANDROID=false IOS_SIMULATOR=true

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then travis_wait 30 $GOPATH/src/github.com/therecipe/qt/internal/ci/linux.sh; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then travis_wait 45 $GOPATH/src/github.com/therecipe/qt/internal/ci/darwin.sh; fi

script:
  - go get -v github.com/therecipe/qt/cmd/...
  - if [[ "$DESKTOP" == "true" ]]; then $GOPATH/bin/qtsetup; fi
  - if [[ "$ANDROID" == "true" ]]; then $GOPATH/bin/qtsetup android; fi
  - if [[ "$IOS" == "true" ]]; then $GOPATH/bin/qtsetup ios; fi
  - if [[ "$IOS_SIMULATOR" == "true" ]]; then $GOPATH/bin/qtsetup ios-simulator; fi
  - if [[ "$QT_WINDOWS_CC" == "true" ]]; then $GOPATH/bin/qtsetup windows; fi
