version: 1.0.{build}
clone_depth: 1
clone_folder: C:\work\src\github.com\therecipe\qt
install:
- cmd: >-
    set PATH=%PATH%;C:\Qt\Qt5.7.0\Tools\mingw530_32\bin

    set GOPATH=C:\work

    set QT_STUB=true


    set QT=qt-opensource-windows-x86-android-5.7.0.exe

    curl -sL --retry 10 --retry-delay 10 -o %TMP%\%QT% https://download.qt.io/official_releases/qt/5.7/5.7.0/%QT%

    %TMP%\%QT% --script %GOPATH%\src\github.com\therecipe\qt\internal\ci\iscript.qs

    DEL %TMP%\%QT% /Q


    set SDK=android-sdk_r24.4.1-windows.zip

    curl -sL --retry 10 --retry-delay 10 -o %TMP%\%SDK% https://dl.google.com/android/%SDK%

    7z x %TMP%\%SDK% -oC:\

    DEL %TMP%\%SDK% /Q


    C:\android-sdk-windows\tools\android.bat list sdk

    echo y | C:\android-sdk-windows\tools\android.bat -s update sdk -f -u -t 1,2,3,5


    set NDK=android-ndk-r12b-windows-x86_64.zip

    curl -sL --retry 10 --retry-delay 10 -o %TMP%\%NDK% https://dl.google.com/android/repository/%NDK%

    7z x %TMP%\%NDK% -oC:\

    DEL %TMP%\%NDK% /Q
build_script:
- cmd: >-
    %GOPATH%\src\github.com\therecipe\qt\setup.bat

    %GOPATH%\src\github.com\therecipe\qt\setup.bat android
